[package]
name = "heaan-ring-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
crypto-bigint = "0.6"
num-complex = "0.4.6"
rustfft = "6.2.0"

[dev-dependencies]
approx = "0.5.1"
criterion = { version = "0.5.1", features = ["html_reports"] }
proptest = "1.6"

[[bench]]
name = "basic"  # Changed from "ring_benchmarks" to "basic"
harness = false
